project: artefacts/IsaacLab-Arena-experiments

version: 0.1.0

jobs:
  unit_tests:
    type: test
    timeout: 15 # minutes
    package:
      docker:
        build:
          dockerfile: empty
    runtime:
      framework: other
      simulator: isaac_sim
      
    scenarios:
      settings:
        - name: navigator_unit_tests
          pytest_file: "nodes/navigator/tests"
          
        - name: policy_controller_unit_tests
          pytest_file: "nodes/policy_controller/tests"
  
  eval:
    type: test
    timeout: 20 # minutes
    package:
      docker:
        build:
          dockerfile: empty
    runtime:
      framework: other
      simulator: isaac_sim
      
    scenarios:
      defaults: # Global to all scenarios, and overriden in specific scenarios.
        output_dirs: ["/tmp/outputs"]
      settings:
        - name: arena_policy_evaluation_test_newton
          metrics: metrics.json
          run: |
            PYTHONPATH=. lerobot-eval \
              --policy.path=Artefacts/act-shape-sorting-so101 \
              --policy.device=cuda \
              --output_dir $ARTEFACTS_SCENARIO_UPLOAD_DIR \
              --env.discover_packages_path=envhub \
              --env.type=shape_sorting_arena \
              --rename_map='{"observation.images.camera_ego_rgb": "observation.images.ego_view", "observation.images.external_camera_rgb": "observation.images.exterior_image"}' \
              --eval.batch_size=1 \
              --eval.n_episodes=1 \
              2>&1
        

