[workspace]
authors = ["Andras Polgar <azazdeaz@gmail.com>"]
channels = ["conda-forge"]
name = "arena_envs"
platforms = [{ platform = "linux-64", glibc = "2.35", cuda = "12.0" }]
version = "0.1.0"

[tasks]
update-submodules = { cmd = "git submodule update --init --recursive" }
install-isaacsim = { cmd = "pip install 'isaacsim[all,extscache]==6.0.1.0' --extra-index-url https://pypi.nvidia.com" }
install-isaaclab = { cmd = "./isaaclab.sh -i", cwd = "./submodules/IsaacLab-Arena/submodules/IsaacLab"}
install = [
    { task = "update-submodules" },
    { task = "install-isaacsim" },
    { task = "install-isaaclab" },
]

[dependencies]
python = "3.12.*"
pip = "*"
rerun-sdk = ">=0.33.1,<0.34"

[pypi-dependencies]
isaaclab-arena = { path = "./submodules/IsaacLab-Arena", editable = true }
arena-envs = { path = "./arena_envs", editable = true }
